### ISSUE TITLE
请教一下，如何爬取微博搜索结果的数据呢？

### ISSUE THREAD

**Issue by iamdaiyuan** [ResolveWang/WeiboSpider#1]
登陆后，尝试爬取 http://s.weibo.com/weibo/关键字&Refer=STopic_box 的数据，但返回的页面似乎无法用xpath和css这类解析，用正则也无从下手，不知你能不能解析。期待能给点思路。

**Comment by ResolveWang** [comment]
不好意思哈，最近有点事情，现在才看到这个issue。有个技巧判断是否有你想要的内容，你可以把返回的代码保存为html，用浏览器打开看是否为你想要的内容，微博这个确实是返回的正确内容。至于你的问题，原因是微博返回的是encode过后的内容，所以需要decode。只有在json.decode()之后你看到的东西才和在浏览器中返回的一样。但是因为python中json的实现有些小缺陷，直接用json.decode()解析返回内容会报错,最初搜索这块我是用java写的，现在才开始改，所以还没放上来。这里我用的是**demjson**，这样就可以正常解析了。请看该项目的关于**search**的文件夹和文件

**Comment by ResolveWang** [comment]
关于抓取后解析的代码我已经更新了，位于do_dataprocess的do_searchprocess模块下，我之前说的用json.decode()的方法我发现很多页面还是不能解析，后面用了**encode('utf-8', 'ignore').decode('unicode-escape', 'ignore')**这个方法才让抓取结果成功显示。这个Issue我就关了，有问题再开Issue

**Comment by ResolveWang** [comment]
现在解析搜索的结果位于 `page_parse/search` 目录下，欢迎查看
