### ISSUE TITLE
转发和@混淆

### ISSUE THREAD

**Issue by yun17** [ResolveWang/WeiboSpider#15]
这是@的链接
`<a target="_blank" render="ext" extra-data="type=atname" href="http://weibo.com/n/%E6%A0%BC%E6%A0%BC?from=feed&amp;loc=at" usercard="name=格格">@格格</a>`

这是转发的链接
`<a target="_blank" render="ext" extra-data="type=atname" href="http://weibo.com/n/%E5%AD%94%E5%B0%8F%E6%B4%9E?from=feed&amp;loc=at" usercard="name=孔小洞">@孔小洞</a>`

除了转发前面会有 // 外好像也没什么区别🙁，您在代码里也没有区分

**Comment by ResolveWang** [comment]
不是的。你可以去转发一条微博试试，你可以手动取消前面两个“//“，但是还是你转发的。转发url我是抓的它的ajax链接，也就是你点击详细转发详情看到的那些内容。如果你需要的是加了 //@这种形式的转发的话，你可以在代码中判断一下就行了
