### ISSUE TITLE
任一抓取时提示：cookie池中不存在cookie  是什么原因

### ISSUE THREAD

**Issue by shiyuzhu** [ResolveWang/WeiboSpider#16]
![image](https://cloud.githubusercontent.com/assets/28074493/26292071/b3cf252c-3ee5-11e7-8188-e837212f7de7.png)

**Comment by yun17** [comment]
你在login_info中有没有账号？

**Comment by shiyuzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/28074493/26294172/671cd8c8-3ef4-11e7-94b6-c20f85c7d984.png)
是账号问题吗

**Comment by shiyuzhu** [comment]
上午 没有提示 账号登录失败    直接显示 不存在cookie

**Comment by ResolveWang** [comment]
问题解决了吗？有问题提issue就是哈。大家懂的就帮忙答复一下

**Comment by ResolveWang** [comment]
如果账号登录需要验证码的，需要在数据库里把need_verify设置为1（默认也是1），设置后需要去云打码上注册一个账号，充值一块钱，用作识别验证码

**Comment by LymanLiuChina** [comment]
新买的一批号嘛, 跑了一会儿 就又出现这种情况,没有cookies了,  每个节点都有 login_queue

**Comment by ResolveWang** [comment]
你要确定一下，你的账号是否被封了，如果被封了，所有cookie都会被删除。如果长期单一ip，可能ip会有一些风险，意思就是，只要你用那个ip的所有账号，都会被要求验证或者别的一些措施

**Comment by LymanLiuChina** [comment]
我换个IP在试试

**Comment by ResolveWang** [comment]
嗯嗯，你可以手动用那些账号在有问题的那个ip试试，看是一个怎么样的效果，如果是被封了，然后你在该ip登一个没被封的账号（最好是一个正常账号，而不是买的低质量的号），再看看效果咋样

**Comment by LymanLiuChina** [comment]
我看到 数据里面 为0 的号 去手动登录了一下,是正常的没有被封,我调整数据库后,我换了一个外网IP后, 直接 login_queuw,home_crawler 命令 还是 显示 没有cookies , 感觉 login_queue这个任务没有执行.

**Comment by ResolveWang** [comment]
那是你的问题了，你需要在启动worker的时候指定login_queue，我看你写成了`login_queue`，不知道你启动命令行的时候是不是这样写的。还有，你可以在从数据库取账号的时候，把取得的账号打印一下，就知道到底取出来没了

**Comment by LymanLiuChina** [comment]
那个是我输入错误,但是, 在celery -A tasks.workers -Q login_queue,user_crawler worker -l info -c 1  上面写道 直接受到 user_crawler 的任务,只有在我手动 Python login_first.py 才会启动login这个任务,是不是每次当cookies池没有cookies ,都必须手动在重新执行一遍 这个文件后 login_queue 这个任务才会执行??

**Comment by ResolveWang** [comment]
不是，有个模块是定时任务，你好好读文档，好好理理思路。

**Comment by ResolveWang** [comment]
定时任务是有一定时间延迟的。
