### ISSUE TITLE
大家都没疑问吗，对这个项目

### ISSUE THREAD

**Issue by ResolveWang** [ResolveWang/WeiboSpider#2]
大家都没疑问吗，对这个项目？是我文档写的太好了，还是代码写的太好了，大家都不提issue啊。很多朋友喜欢加微信交流，不过我建议大家能开issue，问题就可以在issue中统一回答了，方便别人

**Comment by ResolveWang** [comment]
感谢提issue的同学 @yun17 @Zertu

**Comment by haoflynet** [comment]
哈哈😂
