### ISSUE TITLE
is_complete这个方法确实有问题

### ISSUE THREAD

**Issue by yun17** [ResolveWang/WeiboSpider#22]
在抓评论的时候，如果没有评论，那爬虫就会重复尝试，而实际上已经反馈了正确的内容。
这样会消耗爬虫资源。
我也不知道怎么改😂，我自己这边直接给注释了。

**Comment by ResolveWang** [comment]
我去看看

**Comment by ResolveWang** [comment]
不对啊，如果是抓评论的话，它应该不会调用`is_complete`这个方法啊，抓评论是 `user_verify=False`啊，就不会进入 调用 `is_complete`的流程啊

**Comment by yun17** [comment]
哦哦，对哦。我自己改了下想在这里检测下账号状态(lll￢ω￢)，刚改就忘了。
