### ISSUE TITLE
搜索页面验证码

### ISSUE THREAD

**Issue by yun17** [ResolveWang/weibospider#28]
![xuvexhdjcah _67s w 8 jc](https://user-images.githubusercontent.com/16166482/26999955-1ae1971c-4dd8-11e7-957b-b2cb70517269.png)

搜索查看几个页面之后必定出现，频率非常慢也有

应该是微博的防刷热搜机制

**Comment by ResolveWang** [comment]
我在搜索的时候大概10s一次请求，还算比较稳定啊，我只搜索特定关键词。几个账号轮流搜。你是具体怎么操作的

**Comment by yun17** [comment]
可能是我设置时间区间的问题，我再看看能不能解决这个验证码
