### ISSUE TITLE
login_info表少一个need_字段

### ISSUE THREAD

**Issue by JieZhaoAllen** [ResolveWang/WeiboSpider#30]
sql文件中，建表 login_info 时，没有need_验证码 这个字段 ，希望重新更新一下SQL文件

**Comment by ResolveWang** [comment]
你是指的哪个版本？最新版本是已经取消了need_verify这个字段了，现在由程序自动判断是否需要验证码了

**Comment by ResolveWang** [comment]
你建表出问题了吗？直接使用 python create_all.py 建表就行了啊

**Comment by JieZhaoAllen** [comment]
哦哦 ，好的 那我知道了 谢谢啦
