### ISSUE TITLE
微博搜索 机器人验证

### ISSUE THREAD

**Issue by jjhbeloved** [ResolveWang/WeiboSpider#32]
你好，我做 舆情 爬取的时候，会按地区用某些字段进行[内容, 展开全部, 评论]爬取。
间隔是5-8s，16线程，单机。
会存在大量的翻页，差不多爬500-600条数据，微博就会提示我需要输入验证码。
问题:

1. 如果我每次都输入验证码，是否会封号？
2. 是否有好的方式提交 验证码结果? 我现在用 url + post + form 提交，带上cookie 也是无法认证的（自动识别验证码图片这块后续考虑）
3. 我看你们的间隔在3s，15线程，都能爬取3个小时，我顶多就爬几分钟就需要验证码
4. 

是否能解答下？谢谢

**Comment by ResolveWang** [comment]
我觉得第一个问题你也可以自己试。有的时候，输入验证码就可以继续搜索了，有的时候还需要验证手机号，前一种情况较好自动解决，我曾经也实现过，后来发现及时输了验证码，有的时候还会验证手机，所以这段代码没放出来。第二个问题我应该这回答你了吧，如果你要实现的代码，我可以去找找，应该还没删。第三个问题，我想问问你多少账号？还有账号质量如何？这两个因素会影响你的抓取数量。还有，我们前面测试的时候，是抓的用户数据，不同模块微博系统的访问限制也是不同的哈

**Comment by jjhbeloved** [comment]
感谢!
能否提供下 自动验证码校验的**实现代码**？
我暂时只需要 验证码自动校验。
手机号 校验这块我暂时考虑用GUI弹窗手动输入的方式解决。

**Comment by ResolveWang** [comment]
可以，我在方便的时候把它贴到这里来吧

**Comment by ResolveWang** [comment]
核心代码如下
```
    check_url = 'http://weibo.com/p/1005051764222885/info?mod=pedit_more'
    resp = session.get(check_url, headers=headers)
    if is_403(resp.text):
        # import time
        # cur_time = int(time.time() * 100000)
        print('账号{}已被冻结'.format(username))
        soup = BeautifulSoup(resp.text, 'html.parser')
        rid = soup.find(attrs={'id': 'form_secode'}).find(attrs={'name': 'rid'}).get('value')
        pincode_url = 'http://sass.weibo.com/aj/imagecode/image?id={}'.format(rid)
        from PIL import Image
        from io import BytesIO
        r = session.get(pincode_url, headers=headers)
        i = Image.open(BytesIO(r.content))
        i.save('mycode.png')
        verify_code = complite_code_verificate(yundama_username, yundama_password, 'mycode.png')
        verfiy_datas = {
            'secode': verify_code,
            'location': 2,
            'rid': rid,
            'callbackurl': check_url
        }
        verify_resp = session.post('http://sass.weibo.com/aj/imagecode/checkcode', data=verfiy_datas, headers=headers)
        if 'error' in verify_resp.text:
            print('验证码识别失败')
            print(verify_resp.status_code)
        else:
            print(verify_resp.text)
```

要是不懂再问

**Comment by jjhbeloved** [comment]
我这边校验的pincode地址是
http://s.weibo.com/ajax/pincode/verified
请求的报文是 form data格式
secode=csw2&type=sass&pageid=weibo&_t=0
正常响应是
{"code":"100028","msg":"","data":{}}
错误响应是
{"code":"100027","msg":"","data":{}}

是不是find 的rid是图片的 /ajax/pincode/pin?type=sass&amp;ts=1498998737  里面的ts?

**Comment by ResolveWang** [comment]
贴的代码是以前抓包获取到的，我不清楚url是否改变了，你结合抓包和分析js的情况看看吧。

**Comment by ResolveWang** [comment]
现在微博搜索的验证码确实变成了你说的那个url了，ts应该是时间戳，你再好好确定一下，我忘了以前自己的分析过程了，不过这个问题我可能会在下几个版本把它解决了
