### ISSUE TITLE
关于pc端，请求网址构造的问题

### ISSUE THREAD

**Issue by 60ke** [ResolveWang/weibospider#35]
您好，我电脑登陆pc微博，发现，每一页的微博，有动态加载，看了一下请求头是类似于这样的:http://weibo.com/p/aj/v6/mblog/mbloglist?ajwvr=6&domain=100505&from=myfollow_all&is_all=1&pagebar=0&pl_name=Pl_Official_MyProfileFeed__22&id=1005051671103241&script_uri=/amandababe&feed_type=0&page=1&pre_page=1&domain_op=100505&__rnd=1499221602230后面的RND是怎么构造的，或者你是怎么解决动态加载的问题的？

**Comment by ResolveWang** [comment]
rdn按照经验来是时间戳，你把当前时间戳打印出来看看便知道了。细节的话，可以查看代码

**Comment by 60ke** [comment]
好的 谢谢

**Comment by ResolveWang** [comment]
不客气的
