### ISSUE TITLE
建议weibo_data加个字段

### ISSUE THREAD

**Issue by yun17** [ResolveWang/WeiboSpider#4]
加个关键词字段，这样可以分类整理从关键词搜索到的微博。感谢😊

**Comment by yun17** [comment]
不介意的话，我可以帮忙实现😀

**Comment by ResolveWang** [comment]
你好，目前有一个表是keywords，即关键字表，还有一个表示weibo_data，是微博的表，还有一个表示keywords_wbdata，是keywords和weibo_data的中间表。weibo_data的来源有两个，第一个是通过keywords直接在搜索接口中搜索获取的，第二个是抓取用户主页来获取的。所以你说的分类整理从关键词搜到的微博，目前是完全满足需求你，你只需要把weibo_data、keywords_wbdata和keywords做联合查询即可。

**Comment by yun17** [comment]
我这边keywords_wbdata表一直是空的唉，代码里面也没找到keywords_wbdata类使用的地方😯

**Comment by ResolveWang** [comment]
感谢反馈啊，这个给漏掉了，现在补上了。要是有啥逻辑上的问题或者bug，你可以直接给我提PR，有用的话我再合并，把你加到contributor中😊
