### ISSUE TITLE
如何创建表?

### ISSUE THREAD

**Issue by 1634814279** [ResolveWang/weibospider#40]
Readme中的参见SQL表过期了

在运行项目之前，需要在数据库中建表，建表语句参见sql表，也需要把自己的多个微博账号存入表(weibo.login_info)中，把 搜索关键词存入关键词表(keywords)中。这里我已经预插入用户抓取用的一些种子用户了，如果想抓别的用户，请在种子用户表(seed_ids)中做插入操作。

https://github.com/ResolveWang/weibospider/blob/master/config/sql/spider.sql

**Comment by ResolveWang** [comment]
不好意思，readme有的地方更新遗漏了。现在项目通过 `python create_all.py`创建数据表，因此sql文件是多余的，就删了哈。

**Comment by ResolveWang** [comment]
感谢提醒，我去更新一下readme文件，不然可能对用户造成困扰

**Comment by 1634814279** [comment]
秒回不能更棒 感谢回复:)

**Comment by ResolveWang** [comment]
目前添加了[数据库表说明](https://github.com/ResolveWang/weibospider/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E)

**Comment by 1634814279** [comment]
感谢 :)

**Comment by 1634814279** [comment]
既然谢了WIKI能把数据格式一并写入么

**Comment by ResolveWang** [comment]
你指的是数据类型？那个用不着写吧，创建数据库后可以看得到的。

**Comment by 1634814279** [comment]
额本来的意思是 合法的数据格式 比如UID的长度生日的格式什么的 不过仔细看完WIKI像是多此一举了
