### ISSUE TITLE
可以分享到抓到的用户数据吗？

### ISSUE THREAD

**Issue by abigailzeng** [ResolveWang/weibospider#44]
@ResolveWang 在介绍里说抓到了30万用户数据，可以分享一下吗？

**Comment by ResolveWang** [comment]
以前分享过，后来觉得没必要就把链接删了。我待会贴到这里吧

**Comment by ResolveWang** [comment]
链接: https://pan.baidu.com/s/1eR3b5QE 密码: mamr
可能你需要对比一下sql语句的字段和当前项目建表后的字段是否吻合，因为项目迭代过程中某些字段可能会新增或者被删了
