### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by yywing** [ResolveWang/weibospider#47]
在借用你的代码的时候，发现了一个问题
in page_parse/home.py
def get_weibo_list(html):
...
weibo_datas.append(wb_data)    #(140行)
...
wb_data是一个dict，python的按引用传递会把wb_data的地址append进去，循环修改wb_data以后会在整个数组中存的都是最后一条微博的复制内容
但是我并没有用过这个库，并不知道在你这会不会也出现这个bug
我的修改方法是
weibo_datas.append(dict(wb_data))

**Comment by ResolveWang** [comment]
并不是bug，因为每次循环，都会让`wb_data`指向一个新的可变对象。列表追加的也是那个新的可变对象，这个你做一个小实验就能理解我的意思了。
不过还是感谢你提出来。
