### ISSUE TITLE
comsumer: cannot connect to redis://**@127.0.0.1:6397/6 

### ISSUE THREAD

**Issue by LymanLiuChina** [ResolveWang/weibospider#48]
comsumer: cannot connect to redis://**@127.0.0.1:6397/6 : misconf redis is configured to save RDB snapshots, but is currently not able to persist on disk ,commands that may modify the data set are disabled. please check redis logs for details about

**Comment by ResolveWang** [comment]
你这个是没连上redis吧？你自己去仔细阅读该项目的[配置文档](https://github.com/ResolveWang/WeiboSpider/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E7%88%AC%E8%99%AB%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)。

**Comment by ResolveWang** [comment]
具体关于redis的使用问题，可能你得在网上找相关方案。另外，redis需要至少1G的内存，自己掂量一下哈

**Comment by LymanLiuChina** [comment]
开始抓了一会儿 就这样了.  哈哈! 我也是很纠结啊

**Comment by LymanLiuChina** [comment]
restoring 40 unacknowledged message(s)

**Comment by ResolveWang** [comment]
这个我也不太清楚，你调查清楚了可以给我讲一下。这个可能是redis作为broker的一个问题，这里有相关[issue](https://github.com/celery/kombu/issues/305)

**Comment by uyplayer** [comment]
consumer: Cannot connect to redis://:**@127.0.0.1:6379/5: Client sent AUTH, but no password is set.
  

why this error ???

**Comment by thekingofcity** [comment]
please check you spider.yaml at line redis password
