### ISSUE TITLE
有高危号不能搜索关键词

### ISSUE THREAD

**Issue by yun17** [ResolveWang/WeiboSpider#6]
如果账号里面有高危号，应该考虑换个cookies，而不是放弃任务

**Comment by ResolveWang** [comment]
我当时没用高危号做过实验，高危号做搜索的话，系统返回的什么？因为我们要考虑当前账户（ip）到底是被封了还是只是账号由于自身限制，不能进行搜索，却可以进行别的操作。

**Comment by yun17** [comment]
![image](https://cloud.githubusercontent.com/assets/16166482/26247324/f5a7b95e-3ccf-11e7-99fa-fc069e562115.png)
雾霾预警没有获得数据，我也不太明白发生了什么😅
![image](https://cloud.githubusercontent.com/assets/16166482/26247330/fdbc10b8-3ccf-11e7-85e6-0d6e1d233e26.png)

**Comment by ResolveWang** [comment]
你是用的哪类的账号？高危的还是一般的？你要是没搞明白，我明天看看这个东西

**Comment by yun17** [comment]
确定是账号问题，我换了3元一个的号可以正常爬取数据
![image](https://cloud.githubusercontent.com/assets/16166482/26252409/ba777ef6-3ce2-11e7-8ed9-fe8c829a29a9.png)

**Comment by ResolveWang** [comment]
高危号可以采集用户信息。你可以买一元4个的啊，也可以搜索

**Comment by yun17** [comment]
主要是关键词搜索，高危号不行唉

**Comment by ResolveWang** [comment]
嗯嗯
