### ISSUE TITLE
repost_page_crawler 队列永远是空的

### ISSUE THREAD

**Issue by yun17** [ResolveWang/WeiboSpider#8]
![image](https://cloud.githubusercontent.com/assets/16166482/26273265/f150634e-3d5e-11e7-9ce2-edd208b507f3.png)
感觉是不是没有分布爬取第一页之后几页的任务。。都不敢随便暂停worker😥

**Comment by ResolveWang** [comment]
你能看到你抓取的url吗？有的本来就没有转发数据啊，还有的只有第一页转发数据。建议给个具体的url，方便调试

**Comment by yun17** [comment]
http://weibo.com/5053469079/EByw5gpLD?refer_flag=1001030103_
![转发页数](https://cloud.githubusercontent.com/assets/16166482/26274779/58d67bbe-3d84-11e7-98fe-da17502f4882.png)

**Comment by yun17** [comment]
![image](https://cloud.githubusercontent.com/assets/16166482/26274861/6a61c166-3d86-11e7-80a9-9286d6028767.png)
从代码里发现您已经把send_task给注释了

**Comment by yun17** [comment]
有关的代码正在修改调试中，测试完成就提个pr😁

**Comment by ResolveWang** [comment]
好的，谢了。一个人开发和测试，要做的东西太多了，感谢参与

**Comment by ResolveWang** [comment]
是对任务执行成功与否我没多关心，因为网络爬虫有很多不定因素，除非是很重要的数据，一般的数据我就没做重试处理，这个是满足大多数用户的需求，如果需要很精确的结果，确实还需要改进。

**Comment by ResolveWang** [comment]
转发这里耦合性比较强哦，这里如果改为网络调用，必须要注意返回结果哦，因为后面制作转发关系的时候，需要将所有结果拿过来遍历，好做成一个树

**Comment by yun17** [comment]
嗯嗯 ，好的

**Comment by ResolveWang** [comment]
转发这个是有数据的，你在数据库检查了吗？我刚试了抓一条大概600多条的转发微博的数据，基本抓完了的。你截图的那个问题，可能是资源被占用了，没机会执行转发信息抓取
